CREATE TABLE if NOT EXISTS MEDIA_DIRECTORY
(
    ID      integer NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PATH    varchar(255),
    FILENAME    varchar(255),
    CREATED_DATE  timestamp

);


CREATE TABLE if NOT EXISTS MEDIA_FILE
(
    ID      integer NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PATH    varchar(255),
    FILENAME    varchar(255),
    CREATED_DATE  timestamp,
    MEDIA_DIRECTORY_ID integer,
    FOREIGN KEY (MEDIA_DIRECTORY_ID) REFERENCES  MEDIA_DIRECTORY(ID)
);